services:

  duploctl-pipe:
    image: &image duplocloud/pipe:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
      - *image
      - duplocloud/pipe:$VERSION
      x-bake:
        platforms:
        - linux/amd64
        - linux/arm64
    environment:
      DUPLO_HOST: $DUPLO_HOST
      DUPLO_TOKEN: $DUPLO_TOKEN
      DUPLO_TENANT: $DUPLO_TENANT
