services:

  duploctl-pipe:
    image: &image duplocloud/pipe:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
      - *image
      - duplocloud/pipe:${VERSION:-latest}
      x-bake:
        platforms:
        - linux/amd64
        - linux/arm64
    environment:
      HOST: $DUPLO_HOST
      TOKEN: $DUPLO_TOKEN
      TENANT: $DUPLO_TENANT
      KIND: tenant
      CMD: list
      QUERY: '[].AccountName'
