name: Tests

on:
  workflow_dispatch: {}
  workflow_call: {}
  push: {}

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # was unable to biuld with: 3.7, 3.8, or 3.9
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:

    # checkout code 
    - name: Checkout Code
      uses: actions/checkout@v5
    
    # install python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    # install the project
    - name: Install dependencies
      run: pip install .[build,test]
    
    # stop the build if there are Python syntax errors or undefined names
    # ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
    - name: Lint with ruff
      run: ruff check ./src
    
    # run the tests
    - name: Test with pytest
      run: |
        pytest src --junit-xml=test-results.xml

    - name: Surface failing tests
      if: always()
      uses: pmeier/pytest-results-action@main
      with:
        path: test-results.xml
        summary: true
        display-options: fEX
        fail-on-empty: true
